issuer: http://dex:5556/dex
storage:
  type: memory
web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: my-app
    redirectURIs:
      - 'http://localhost:3000/callback'
    name: 'My Test App'
    secret: my-secret

enablePasswordDB: true
staticPasswords:
  - email: "test@example.com"
    hash: "$2y$05$olu30d4lgn7r1/Xfe13N1.5dz0N9AVlKXUFIxXUYVkhiq8D6gwYGG"
    username: "test"
    userID: "1234"
