version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pwd2020Db
    ports: 
      - 16000:5432

  mariadb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 16004:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Pwd2020Db

  mysql-ssh:
    build: mysql-ssh
    restart: always
    ports: 
      - 16005:3306
      - 16006:22
