name: Build test containers

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
    paths:
      - e2e-tests/containers/**

jobs:
  build-docker-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build mysql-ssh-login image
        run: |
          docker build -t dbgate/mysql-ssh-login:latest e2e-tests/containers/mysql-ssh-login

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GHCR
        run: |
          docker tag dbgate/mysql-ssh-login:latest ghcr.io/dbgate/mysql-ssh-login:latest
          docker push ghcr.io/dbgate/mysql-ssh-login:latest
