name: E2E tests
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'

jobs:
  test-runner:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y xvfb libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: yarn install
        run: |
          yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: yarn prepare:packer
          start: node packer/build/bundle.js --listen-api --static-dir packer/build/public
          project: ./e2e-tests
          
    services:
      mysql:
        image: mysql:8.0.18
        env:
          MYSQL_ROOT_PASSWORD: Pwd2020Db
        ports:
          - 16004:3306
