name: E2E tests
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'

jobs:
  test-runner:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y xvfb libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: yarn install
        run: |
          yarn install
      - name: Build
        run: |
          yarn prepare:packer
      - name: yarn install cypress
        run: |
          cd e2e-tests
          yarn install
      - name: Start backend server
        run: |
          node packer/build/bundle.js --listen-api --run-packer-build &
          echo $! > backend.pid
      - name: Run Cypress tests
        run: |
          cd e2e-tests
          yarn cy:run
        env:
          CI: true
      - name: Stop backend server
        run: |
          kill $(cat backend.pid)
          rm backend.pid

    services:
      mysql:
        image: mysql:8.0.18
        env:
          MYSQL_ROOT_PASSWORD: Pwd2020Db
        ports:
          - 16004:3306
