name: E2E tests
on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y xvfb libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: yarn install
        run: |
          yarn install
      - name: Build
        run: |
          yarn prepare:packer
      - name: yarn install cypress
        run: |
          cd e2e-tests
          yarn install
      - name: Run Cypress tests
        run: |
          cd e2e-tests
          yarn test:ci

    services:
      mysql:
        image: mysql:8.0.18
        env:
          MYSQL_ROOT_PASSWORD: Pwd2020Db
